---
title: "STAT 98 Project 2 Simulation"
author: "Chris Canzano, Victoria Li, and Henry Wu"
date: "March 17, 2024"
output:
  pdf_document: default
  html_notebook: default
---

```{r setup}
library(mgcv) # adds the package for multivariate normal data generation
```

```{r}
set.seed(98) # set seed for reproducibility
N <- 10000 # number of trials in each configuration - reduce this number to like 100 when you do test runs!!
n <- 100 # sample size
k <- 4 # number of predictor variables
cases <- c('treatment', 'control', 'all') # 'all' refers to the configuration with strong multicollinearity
treatment_rhos <- c(0, 0.7, -0.7, 0.99, -0.99) # correlations in configuration with collinearity between treatment and one control (as well as no collinearity)
control_rhos <- c(0.99, -0.99) # correlations in configuration with collinearity between two controls
var_epsilons <- c(1, 25) # variances of error term - let me know if I should change these to be more reasonable (after we do some test runs)
coef_sets <- list(c(2, 1, 0.5, 0.5), c(2, -1, -0.5, -0.5), c(0.5, 0.5, 1, 2)) # sets of coefficients - let me know if I should change these to be more reasonable (after we do some test runs)

for (case in cases) {
  if (case == 'treatment') {
    rhos <- treatment_rhos
  }
  else if (case == 'control') {
    rhos <- control_rhos
  }
  else if (case == 'all') {
    rhos <- c(1) # only one case which does not have variable rhos
  }
  
  for (rho in rhos) {
    if (case == 'treatment') {
      Sigma <- matrix(c(1, rho, 0, 0,
                        rho, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1), 4, 4) # correlation matrix for collinearity between treatment and one control
    }
    else if (case == 'control') {
      Sigma <- matrix(c(1, 0, 0, 0,
                        0, 1, rho, 0,
                        0, rho, 1, 0,
                        0, 0, 0, 1), 4, 4) # correlation matrix for collinearity between two controls
    }
    else if (case == 'all') {
      Sigma <- matrix(c(1, 0.992, 0.621, 0.465,
                        0.992, 1, 0.604, 0.446,
                        0.621, 0.604, 1, -0.177,
                        0.465, 0.446, -0.177, 1), 4, 4) # correlation matrix for strong multicollinearity - based on Longley's economic data
    }
    print('Correlation matrix:')
    print(Sigma)
    # print(paste('Theoretical condition number:', 1/rcond(Sigma)))
    for (coefs in coef_sets) {
      print(paste('Coefficients: [', paste(coefs, collapse=', '), ']', sep=''))
      for (var_epsilon in var_epsilons) {
        print(paste('Variance of error term: =', var_epsilon))
        for (i in 1:N) {
          X <- rmvn(n, rep(0, k), Sigma) # generation of multivariate normal data
          # print(X[1:10,]) # first 10 observations of data
          # print(paste('Condition number:', 1/rcond(t(scale(X)) %*% scale(X)))) # using empirical correlation matrix on standardized data
          epsilon <- rnorm(n, 0, sqrt(var_epsilon)) # generation of error term
          y <- X %*% coefs + epsilon # generation of response variable
          # print(y[1:10]) # first 10 observations of response variable
        }
      }
    }
  }
  print('')
}
```